package de.hamedtanha.servertoolkit.ui.designsystem.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.Shapes
import androidx.compose.material3.Typography
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

enum class DynamicColorPolicy {
    Disabled,
    AllowedWhenSupported,
}

data class ServerToolkitVisualProfile(
    val lightColorScheme: ColorScheme,
    val darkColorScheme: ColorScheme,
    val typography: Typography,
    val shapes: Shapes,
    val spacing: ServerToolkitSpacing,
    val dynamicColorPolicy: DynamicColorPolicy,
)

private val ServerToolkitLightColorScheme = lightColorScheme(
    primary = LightPrimary,
    onPrimary = LightOnPrimary,
    primaryContainer = LightPrimaryContainer,
    onPrimaryContainer = LightOnPrimaryContainer,
    inversePrimary = LightInversePrimary,
    secondary = LightSecondary,
    onSecondary = LightOnSecondary,
    secondaryContainer = LightSecondaryContainer,
    onSecondaryContainer = LightOnSecondaryContainer,
    tertiary = LightTertiary,
    onTertiary = LightOnTertiary,
    tertiaryContainer = LightTertiaryContainer,
    onTertiaryContainer = LightOnTertiaryContainer,
    background = LightBackground,
    onBackground = LightOnBackground,
    surface = LightSurface,
    onSurface = LightOnSurface,
    surfaceVariant = LightSurfaceVariant,
    onSurfaceVariant = LightOnSurfaceVariant,
    surfaceTint = LightPrimary,
    inverseSurface = LightInverseSurface,
    inverseOnSurface = LightInverseOnSurface,
    error = LightError,
    onError = LightOnError,
    errorContainer = LightErrorContainer,
    onErrorContainer = LightOnErrorContainer,
    outline = LightOutline,
    outlineVariant = LightOutlineVariant,
    scrim = ServerToolkitScrim,
    surfaceDim = LightSurfaceDim,
    surfaceBright = LightSurfaceBright,
    surfaceContainerLowest = LightSurfaceContainerLowest,
    surfaceContainerLow = LightSurfaceContainerLow,
    surfaceContainer = LightSurfaceContainer,
    surfaceContainerHigh = LightSurfaceContainerHigh,
    surfaceContainerHighest = LightSurfaceContainerHighest,
    primaryFixed = FixedPrimary,
    primaryFixedDim = FixedPrimaryDim,
    onPrimaryFixed = FixedOnPrimary,
    onPrimaryFixedVariant = FixedOnPrimaryVariant,
    secondaryFixed = FixedSecondary,
    secondaryFixedDim = FixedSecondaryDim,
    onSecondaryFixed = FixedOnSecondary,
    onSecondaryFixedVariant = FixedOnSecondaryVariant,
    tertiaryFixed = FixedTertiary,
    tertiaryFixedDim = FixedTertiaryDim,
    onTertiaryFixed = FixedOnTertiary,
    onTertiaryFixedVariant = FixedOnTertiaryVariant,
)

private val ServerToolkitDarkColorScheme = darkColorScheme(
    primary = DarkPrimary,
    onPrimary = DarkOnPrimary,
    primaryContainer = DarkPrimaryContainer,
    onPrimaryContainer = DarkOnPrimaryContainer,
    inversePrimary = DarkInversePrimary,
    secondary = DarkSecondary,
    onSecondary = DarkOnSecondary,
    secondaryContainer = DarkSecondaryContainer,
    onSecondaryContainer = DarkOnSecondaryContainer,
    tertiary = DarkTertiary,
    onTertiary = DarkOnTertiary,
    tertiaryContainer = DarkTertiaryContainer,
    onTertiaryContainer = DarkOnTertiaryContainer,
    background = DarkBackground,
    onBackground = DarkOnBackground,
    surface = DarkSurface,
    onSurface = DarkOnSurface,
    surfaceVariant = DarkSurfaceVariant,
    onSurfaceVariant = DarkOnSurfaceVariant,
    surfaceTint = DarkPrimary,
    inverseSurface = DarkInverseSurface,
    inverseOnSurface = DarkInverseOnSurface,
    error = DarkError,
    onError = DarkOnError,
    errorContainer = DarkErrorContainer,
    onErrorContainer = DarkOnErrorContainer,
    outline = DarkOutline,
    outlineVariant = DarkOutlineVariant,
    scrim = ServerToolkitScrim,
    surfaceDim = DarkSurfaceDim,
    surfaceBright = DarkSurfaceBright,
    surfaceContainerLowest = DarkSurfaceContainerLowest,
    surfaceContainerLow = DarkSurfaceContainerLow,
    surfaceContainer = DarkSurfaceContainer,
    surfaceContainerHigh = DarkSurfaceContainerHigh,
    surfaceContainerHighest = DarkSurfaceContainerHighest,
    primaryFixed = FixedPrimary,
    primaryFixedDim = FixedPrimaryDim,
    onPrimaryFixed = FixedOnPrimary,
    onPrimaryFixedVariant = FixedOnPrimaryVariant,
    secondaryFixed = FixedSecondary,
    secondaryFixedDim = FixedSecondaryDim,
    onSecondaryFixed = FixedOnSecondary,
    onSecondaryFixedVariant = FixedOnSecondaryVariant,
    tertiaryFixed = FixedTertiary,
    tertiaryFixedDim = FixedTertiaryDim,
    onTertiaryFixed = FixedOnTertiary,
    onTertiaryFixedVariant = FixedOnTertiaryVariant,
)

internal val DefaultServerToolkitVisualProfile =
    ServerToolkitVisualProfile(
        lightColorScheme = ServerToolkitLightColorScheme,
        darkColorScheme = ServerToolkitDarkColorScheme,
        typography = ServerToolkitTypography,
        shapes = ServerToolkitShapes,
        spacing = DefaultServerToolkitSpacing,
        dynamicColorPolicy = DynamicColorPolicy.Disabled,
    )
